### ISSUE TITLE
Can you build the .jar file , so we can download it :) ?

### ISSUE THREAD

**Issue by goxr3plus** [forecasted/jnotify#1]
I was desperately searching for this and i found you have made it available on GitHub ye!!!!!!

But i need the jnotify.jar

Can you provide it ? Similar repository with JNotify like your but with jnotify.jar builded is https://github.com/skiyo/JNotify

**Comment by goxr3plus** [comment]
Ok i builded it  
[jnotify-0.9.4.zip](https://github.com/forecasted/jnotify/files/805454/jnotify-0.9.4.zip)

But when trying to use it i am getting the below error :(

```
Exception in thread "main" java.lang.NoClassDefFoundError: org/fusesource/hawtjni/runtime/Library
	at net.contentobjects.jnotify.JNotify.loadLibrary(JNotify.java:118)
	at net.contentobjects.jnotify.JNotify.<clinit>(JNotify.java:72)
	at Sample.sample(Sample.java:26)
	at Sample.<init>(Sample.java:8)
	at Sample.main(Sample.java:44)
Caused by: java.lang.ClassNotFoundException: org.fusesource.hawtjni.runtime.Library
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 5 more

```

**Comment by forecasted** [comment]
maven package hawtjni-runtime is required.

By the way, which is your os version?

**Comment by goxr3plus** [comment]
OS: Windows 10

I have tried to build it with Eclipse .

It produces the .jar but the error mentioned above is occuring when trying
to run it with the default JNotify example .

I need to install that package in order to produce a correct jar file?

When i check the inside classes and folders it seems that it has all the
needed files.

i dont know why it gives that error ☺.

**Comment by forecasted** [comment]
I fixed some bug of jnotify in Windows 10 just now. Please update and run maven install. 

I also added a test project testJnotify including a pom file, https://github.com/forecasted/testJnotify. Have a try.

**Comment by goxr3plus** [comment]
I successfully build it and it works :) Have you tested it on Linux etc? 
[jnotify-all-0.9.4.zip](https://github.com/forecasted/jnotify/files/815404/jnotify-all-0.9.4.zip)

Although why to use one more external library? `hawtjni-runtime-1.11`

What is the benefits of using your project and not  https://github.com/skiyo/JNotify ?
The second is one file and no any external libraries... 

I would be glad to hear from you about the above , then i can close the issue :)
